language: node_js
node_js:
   - "7"
branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod

deploy:
  - provider: azure_web_apps
  - verbose: true
